#!/bin/env bash

# 输入一个数字 N
# 然后输入 N 个数，并计算它们的平均数, 保留三个小数点

read num;

if [ $num -lt 1 -o $num -gt 500 ]; then
    echo 'N should be 1<=N<=500'
    exit 0
fi

for ((i=0; i<num; i++)); do
    read num$i

    tmp=num$i
#eval var=\$$tmp
    var=${!tmp}
    if [ $var -lt -10000 -o $var -gt 10000 ]; then
        echo 'x should be -10000<=x<=10000'
    fi
done

unset var
total=0
for ((i=0; i<num; i++)); do
    tmp=num$i
#eval var=\$$tmp
    var=${!tmp}
    let total+=var
done
echo "scale=3; $total/$num" | bc -l

