#!/bin/env bash

# 输入三个整数，代表三角形的三条边
# 查看这个三角形是：等边，等腰，不等边?
# 限制：1 <= x,y,z <= 1000, 任何两个数相加大于第三个数

read x; read y; read z;

# 判断整数x是否符合要求
valid()
{
    local flag=0

    for i in $@
    do
        if [ $i -ge 1 -a $i -le 1000 ];
        then
            :
        else
            let flag=1
        fi
    done

    if [[ $(($1+$2))>$3 && $(($1+$3))>$2 && $(($2+$3))>$1 ]];
    then
        echo 'w'
        :
    else
        echo 'h'
        let flag=1
    fi

    return $flag
}

# 判断三角形类型
triangle()
{
    if [ $1 -eq $2 -a $1 -eq $3 ];
    then
        echo 'EQUILATERAL'
    fi
}

valid $x $y $z

if [ $? == 1 ];
then
    echo 'x,y,z 需要符合 1<=N<=1000, 并且任意两个数相加大于第三个数'
    exit 1
fi

triangle $x $y $z
exit 0
